import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";

import Header from "./(main)/_components/header";

import { Playfair_Display } from 'next/font/google';

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'], // Choose weights you need
  variable: '--font-playfair', // Optional: for CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${playfair.className}`}
      >
        <NextIntlClientProvider >
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
