import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { Inter } from 'next/font/google'
import Header from "./(main)/_components/Header";
import { getLocale } from "next-intl/server";

const inter = Inter({
  subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale} className={inter.className}>
      <body
      >
        <NextIntlClientProvider >
          <Header />
          {children}
        </NextIntlClientProvider>
        {children}
      </body>
    </html>
  );
}
