import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";

import Header from "./(main)/_components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <NextIntlClientProvider >
          <Header />
          {children}
        </NextIntlClientProvider>
        {children}
      </body>
    </html>
  );
}
